enum Alignment {
    TOPLEFT, TOP, TOPRIGHT,
    LEFT, MIDDLE, RIGHT,
    BOTTOMLEFT, BOTTOM, BOTTOMRIGHT
}

enum ButtonState {
    DEFAULT, DISABLED, HIGHLIGHTED, PRESSED
}

enum EditBoxState {
    DEFAULT, ERROR, OK
}